name: 'SonarQube'
description: 'Run dotnet scans'
inputs:
  option:  
    description: 'start or stop dotnet scan'
    required: true
    default: 'start'
  # working-directory:  
  #   description: 'directory to start and stop the scan'
  #   required: true
  #   default: './ci'
  
    
outputs:
  sonarqube-report:
    description: "SonarQube Report"
    value: "Report"
runs:
  using: 'node12'
  main: 'dist/index.js'